version: '3'
services:
  live-server:
    container_name: live-server
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - "1935:1935"
      - "8080:8080"
    environment:
      - cpus=1